### PR TITLE
Add Procast iOS and Android clients

### PR DESCRIPTION
**Pull request by nosyjoe**
Adds a new client, Procast, to packages/clients/src/procast for platforms android and ios, including a svg icon

### CODE REVIEW

**Comment by nosyjoe** [comment]
Should I update the index.js and readme as well?

**Comment by alexander-heimbuch** [comment]
Thanks for the contribution, I would highly appreciate if you adapt the index and readme as well :)

**Comment by saerdnaer** [comment]
@nosyjoe 🔝

**Comment by nosyjoe** [comment]
done 🚀 anything else that I should do or could help you with?

Btw, is there a reason some clients have multiple entries in the README (e.g. podcat)?

**Comment by alexander-heimbuch** [comment]
@nosyjoe potentially just typos :D

**Pull request merged**
