### PR TITLE
feat: Add typescript types for web player

### PR DESCRIPTION
**Pull request by JumpLink**
For my internal project I have created typescript types for the web player. With this PR I want to transfer them from my project to your main project.

The package.json has no `main`, `module` or `browser` entry, so I wasn't sure how to resolve the `embed.js` file via npm. The new `types` entry resolves the typescript types, but it could be that this doesn't work correctly without the main / browser entries. 

So maybe you need to add the following to the package.json of the web player:
```json
  "main": "dist/embed.js",
  "browser": "dist/embed.js",
```
Maybe it makes sense to add a typescript example as well.

If there are any adjustments desired please let me know.

### CODE REVIEW

**Comment by alexander-heimbuch** [comment]
Thank you very much 🙏 Could you move the typings to `/packages/types`? That would enable me to create a dedicated package just for the types 👍

**Comment by JumpLink** [comment]
okay

**Comment by JumpLink** [comment]
@alexander-heimbuch Okay I moved them and also created a README.md and package.json. I did this now without testing it, but you will probably adjust this anyway?

**Comment by alexander-heimbuch** [comment]
Sorry for the late response, it was quite a busy week :) As soon as the next player gets released it will be available via `@podlove/types` 👍

**Pull request merged**
